# Generated by Django 5.2.5 on 2026-04-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waitboard',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('w_name', models.CharField(max_length=100)),
                ('w_hp', models.CharField(max_length=20)),
                ('w_created_at', models.DateTimeField(auto_now_add=True)),
                ('w_YN', models.CharField(default='N', max_length=1)),
            ],
        ),
    ]
