# Generated by Django 5.2.5 on 2026-07-02 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMember',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('admin_idx', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(db_column='id', max_length=100, unique=True)),
                ('password', models.CharField(db_column='pwd', max_length=100)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('admin_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '관리자',
                'db_table': 'admin_member',
                'ordering': ['-admin_idx'],
            },
        ),
    ]
