# Generated by Django 5.2.5 on 2026-07-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_event_member_deltype'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterecord',
            name='mem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='member.event_member'),
        ),
    ]
