# Generated by Django 5.2.5 on 2026-07-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_voterecord_mem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterecord',
            old_name='mem_id',
            new_name='mem_idx',
        ),
    ]
