# Generated by Django 5.2.5 on 2026-07-22 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_rename_mem_id_voterecord_mem_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterecord',
            old_name='candidate_id',
            new_name='candidate',
        ),
    ]
