# Generated by Django 5.2.5 on 2026-06-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_member',
            fields=[
                ('mem_idx', models.AutoField(primary_key=True, serialize=False)),
                ('mem_id', models.CharField(max_length=50)),
                ('mem_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mem_hospital', models.CharField(blank=True, max_length=500, null=True)),
                ('mem_email1', models.CharField(blank=True, max_length=100, null=True)),
                ('mem_email2', models.CharField(blank=True, max_length=100, null=True)),
                ('mem_HP', models.CharField(blank=True, max_length=50, null=True)),
                ('mem_Event', models.SmallIntegerField()),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('mem_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('mem_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('mem_hos_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('mem_input_date', models.DateTimeField()),
                ('Event_location', models.CharField(blank=True, max_length=1, null=True)),
                ('mem_Depart', models.CharField(blank=True, max_length=100, null=True)),
                ('mem_teamName', models.CharField(blank=True, max_length=200, null=True)),
                ('mem_SalesName', models.CharField(blank=True, max_length=200, null=True)),
                ('mem_duty', models.CharField(blank=True, max_length=100, null=True)),
                ('mem_YN', models.CharField(blank=True, max_length=1, null=True)),
                ('Country', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(blank=True, max_length=100, null=True)),
                ('mem_dept', models.CharField(blank=True, max_length=500, null=True)),
                ('account_code', models.CharField(blank=True, max_length=30, null=True)),
                ('use_YN', models.CharField(blank=True, max_length=1, null=True)),
                ('mem_pwd', models.CharField(blank=True, max_length=20, null=True)),
                ('dc_licence', models.CharField(blank=True, max_length=30, null=True)),
                ('connect_path', models.CharField(blank=True, max_length=1, null=True)),
                ('etc_text', models.CharField(blank=True, max_length=500, null=True)),
                ('event_gubun', models.CharField(blank=True, max_length=1, null=True)),
                ('work_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('depositor', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.CharField(blank=True, max_length=8, null=True)),
                ('mail_YN', models.CharField(blank=True, max_length=1, null=True)),
                ('memTranspor', models.CharField(blank=True, max_length=1, null=True)),
                ('mem_birth', models.CharField(blank=True, max_length=8, null=True)),
                ('mem_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=200, null=True)),
                ('mem_agree', models.CharField(blank=True, max_length=1, null=True)),
                ('hospital_address', models.CharField(blank=True, max_length=200, null=True)),
                ('Affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('Dietary', models.CharField(blank=True, max_length=30, null=True)),
                ('Dietary_Etc', models.CharField(blank=True, max_length=500, null=True)),
                ('mem_Depart_kor', models.CharField(blank=True, max_length=200, null=True)),
                ('mem_Text', models.CharField(blank=True, max_length=2000, null=True)),
                ('mem_name_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('mem_hospital_eng', models.CharField(blank=True, max_length=500, null=True)),
                ('tp1', models.CharField(blank=True, max_length=30, null=True)),
                ('tp2', models.CharField(blank=True, max_length=30, null=True)),
                ('tp3', models.CharField(blank=True, max_length=30, null=True)),
                ('tp4', models.CharField(blank=True, max_length=30, null=True)),
                ('Allergy', models.CharField(blank=True, max_length=30, null=True)),
                ('Allergy_Etc', models.CharField(blank=True, max_length=500, null=True)),
                ('DelType', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('DelDate', models.DateTimeField(blank=True, null=True)),
                ('add_info', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'event_member',
                'ordering': ['-mem_idx'],
            },
        ),
    ]
