# Generated by Django 5.2.5 on 2026-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_member',
            name='DelType',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
