# Generated by Django 5.2.5 on 2026-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('car_idx', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=100)),
                ('car_order', models.CharField(max_length=100)),
                ('car_field', models.CharField(max_length=30)),
                ('car_year', models.CharField(max_length=4)),
                ('car_day', models.CharField(max_length=100)),
                ('car_date', models.DateTimeField()),
                ('car_url', models.CharField(max_length=100)),
                ('car_size_h', models.IntegerField()),
                ('car_size_w', models.IntegerField()),
                ('car_check', models.CharField(max_length=3)),
                ('car_readnum', models.IntegerField()),
                ('car_content', models.CharField(max_length=500)),
                ('car_image', models.CharField(max_length=100)),
                ('car_choo', models.IntegerField()),
                ('car_soonwe', models.IntegerField()),
            ],
            options={
                'verbose_name': '행사',
                'verbose_name_plural': '행사',
                'db_table': 'board',
                'ordering': ['-car_idx'],
            },
        ),
    ]
