# Generated by Django 5.2.5 on 2026-06-22 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='car_check',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_choo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_image',
            field=models.FileField(blank=True, null=True, upload_to='boardimg/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_readnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_size_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_size_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_soonwe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='car_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
