# Generated by Django 5.2.5 on 2026-06-22 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_car_check_alter_board_car_choo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='car_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
